### ISSUE TITLE
Table functionality in TipTap Editor is limited

### ISSUE THREAD

**Issue by petergross** [django-cms/djangocms-text#21]
I've implemented the TipTap editor with djangocms_text however the ability to add or remove rows or columns is not available to the user. Currently a 3x3 table is created by default but the user doesn't have the ability to change the table. The documentation doesn't indicate whether there are additional settings that need to be made either. I've followed the installation instructions and am able to edit text, it is just the table functionality that is an issue.

**Comment by fsbraun** [comment]
@petergross Yes, that's correct.

Currently, there is no editing functionality for tables. The Tiptap table plugin is installed by default (but does not have a user interface), so that existing tables can be shown in the editor. You cannot, however, edit them in a meaningful way.

The "Table" icon needs to be removed from the toolbar.

Obviously, it would be great to have tables available, but someone would beed to create a PR to add an UI.

For now, you can use the CKEditor4 RTE, or the CKEditor5 RTE (https://github.com/django-cms/djangocms-text-ckeditor5) which have table UI. CKEditor 5 does not support dynamic links or text-enabled plugin for now.
